---
title: "TopModel_fromScratch"
output: html_document
date: "2023-02-23"
---

2/23/23
- I am trying to make topmodel from scratch to test two ideas kevin and JP had:
  - modifying twi based on soil location and properties
  - modifying infiltration properties based on soil location and properties
    
```{r, echo = FALSE}
#setup
library(pacman)

p_load(tidyverse, raster, rgdal, sp,
       rgeos, spdplyr, whitebox, RColorBrewer, lubridate,
       tmap)
```
  
```{r}
#dem <- raster("./w3_dem.tif")
dem <- "./w3_dem.tif"

#wbt_fill_single_cell_pits(
#                    dem = "McDonaldHollowDEM/brushDEMsm_5m_crs.tif",
 #                   output = "McDonaldHollowDEM/bmstationdem_filled.tif")

breach_output <- "./w3_dems/w3_dem_breached.tif"
wbt_breach_depressions_least_cost(
  dem = dem,
  output = breach_output,
  dist = 5,
  fill = TRUE)

fill_output <- "./w3_dems/w3_dem_filled.tif"
wbt_fill_depressions_wang_and_liu(
  dem = breach_output,
  output = fill_output
)

flowacc_output <- "./w3_dems/w3_dem_flowacc.tif"
wbt_d_inf_flow_accumulation(input = fill_output,
                            output = flowacc_output,
                            out_type = "Specific Contributing Area")

slope_output <- "./w3_dems/w3_dem_slope.tif"
wbt_slope(dem = fill_output,
          output = slope_output,
          units = "degrees")

twi_output <- "./w3_dems/w3_dem_twi.tif"
wbt_wetness_index(sca = flowacc_output, #flow accumulation
                  slope = slope_output,
                  output = twi_output)

twi <- raster(twi_output)
dem <- raster(dem)
plot(twi)

```

Show topographic wetness index
```{r}
thresh <- 11
twi_threshold <- twi
twi_threshold[twi_threshold < thresh] <- NA

hist(twi, breaks = 50)
plot(twi_threshold, col = "blue")

twi_frame <- getValues(twi)
twi_frame <- twi_frame[!is.na(twi_frame)]
m <- mean(twi_frame)
n <- length(twi_frame)


Fmax <- length(twi_frame[twi_frame >= m])/n
Fmax * exp(-0.5 * m)


```

Now actually build model
```{r}
#modelling after Bevin and kirkby 1979
#already found the twi above

#approximating lambda
#first calculate area of raster
#get sizes of all cells in raster [km2]
cell_size <- area(dem, na.rm=TRUE, weights=FALSE)
#delete NAs from vector of all raster cells
##NAs lie outside of the rastered region, can thus be omitted
cell_size <- cell_size[!is.na(cell_size)]
#compute area [km2] of all cells in geo_raster
raster_area <- length(cell_size)*median(cell_size)
#print area of Georgia according to raster object
A <- raster_area #area in meters
#Bailey et al. 2014 says it is 42 hectares

Lambda <- (1/A) * cellStats(twi, "sum") * A

twi_frame <- getValues(twi)
twi_frame <- twi_frame[!is.na(twi_frame)]


Excess_rainfall <- i - imax
er <- 0 #potential ET once S1 is depleted
m <- 0 #constant affecting the storage of S3


#stores
S1 <- 0 #interception store [mm3]
S2 <- 0 #infiltration store [mm3]
S3 <- 0 #saturated zone store [mm3]
ch <- 0 #channel flow [mm3]

#fluxes
SD <- 0 #max value of S1, must fill before infiltration, loss from interception to evaporation
Sc <- 0 #loss from infiltration to evaporation
P <- 0 #input from precipitation
qof <- i * Ac #quick return flow [mm2 hr-1]
qo <- if(S3 == 0) 10 else 0 #base flow
qb <- qo * ln(S3 / m) #delayed flow
ea <- er * S2 / Sc #actual evaporation from infiltration store, evaporation at a decreasing rate due to S2
Si <- 0 #relative storage [mm]

precip <- read.csv() #file containing precip record
timestep <- 1 #hr
duration <- 7 * 24 #hr, can also be length of precip record
time <- seq(1, duration, timestep)

#using values from Beven and Kirkby to start
parms <- c(
  2.5, #SD, max value of S1, must fill before infiltration, loss from interception to evaporation
  1, #Sc, loss from infiltration to evaporation
  15, #io, constant leakage rate from S2 to S3
  0, #b, a parameter controlling when S2 stops contributing to subsurface and when it starts running off the surface
  100, #m, a constant affecting the storage of S3
  10000 #basin area in m2
)

topmodel <- function(t, states, parms, precip, twi){ 
  #states: how much is in each store at this time step
  S1 <- states[1] #interception [mm]
  S2 <- states[2] #infiltration [mm]
  S3 <- states[3] #saturated zone store [mm]
  quick <- states[4] 
  delayed <- states[5]
  
  #parameters
  SD <- parms[1] #max value of S1
  Sc <- parms[2] #loss from infiltration to evaporation
  io <- parms[3] #constant leakage rate from S2 to S3
  b <- parms[4]
  m <- parms[5] #constant affecting the storage of S3
  A <- parms[6] #area of entire basin
  ST <- parms[7] #local maximum storage area value [mm], capacity

  i <- precip #rainfall rate [mm/hr], input to S2 unless i > imax = io + b/S2
  imax <- max(precip) #maximum rainfall rate
  
  Ac <- length(twi[twi > ST/m]) #variable contributing area; rain    falling on this immediately becomes overland flow
  P <- (A - Ac)  #non-active area
  
  #flux equations
  precipitation <- precip
  evaporation <- evap
  interception <- if(S1 < SD) P - Sc else 0
  infiltration <- if(i > imax & i == io + b/S2) 0 else interception
  saturatedZone <- 0
  
  #derivatives
  dS1_dt <- precipitation - evaporation - Ac
  dS2_dt <- infiltration - evaporation - Ac
  dS3_dt <- saturatedZone - evaporation
  
  
}

```

